flaskblog/gallery/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from flaskblog.models import Gallery
from wtforms.validators import DataRequired
from flask_uploads import UploadSet, IMAGES, configure_uploads


photos = UploadSet('photos', IMAGES)


class GalleryForm(FlaskForm):
    filepath = StringField('Filepath', validators=[DataRequired()])
    location = StringField('Location', validators=[DataRequired()])
    caption = StringField('Caption', validators=[DataRequired()])
    submit = SubmitField('Upload to Gallery')

flaskblog/project/forms.py
from flask_wtf import FlaskForm
from flask_wtf.html5 import URLField
from wtforms import StringField, SubmitField
from flaskblog.models import Project
from wtforms.validators import DataRequired, url
from flask_uploads import UploadSet, IMAGES, configure_uploads


photos = UploadSet('photos', IMAGES)


class ProjectForm(FlaskForm):
    filepath = StringField('Filepath', validators=[DataRequired()])
    link = URLField('Url', validators=[url()])
    title = StringField('Title', validators=[DataRequired()])
    language = StringField('Technologies', validators=[DataRequired()])
    caption = StringField('Caption', validators=[DataRequired()])
    submit = SubmitField('Upload to Portfolio')

flaskblog/gallery/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db, basic_auth
from flask_basicauth import BasicAuth
from flaskblog.models import Gallery
from flaskblog.gallery.forms import GalleryForm
from flaskblog.users.utils import save_picture

gall = Blueprint('gall', __name__)

@gall.route("/gallery/new", methods=['GET', 'POST'])
@basic_auth.required
def new_image():
    form = GalleryForm()
    if form.validate_on_submit():
        gallerys = Gallery(filepath=form.filepath.data, location=form.location.data, caption=form.caption.data)
        db.session.add(gallerys)
        db.session.commit()
        flash('Your image has been uploaded!', 'success')
        return redirect(url_for('gall.gallery'))
    return render_template('create_gallery.html', title='New Image', form=form)

#new
gallery = ""

@gall.route("/gallery")
def gallery():
    gallery = Gallery.query.order_by(Gallery.location.desc())
    return render_template('gallery.html', images=images, title='Gallery', gallery=gallery)

# data
images = [
    {
        'filepath': 'static/photos/gallery/about_me.jpg',
        'location': 'Spokane, WA',
        'caption': 'Me in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/cathedralTwo.jpg',
        'location': 'Spokane, WA',
        'caption': 'Cathedral in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/christmasTexas.jpg',
        'location': 'Fort Worth, TX',
        'caption': 'Christmas Tree in Sundance Square'
    },
    {
        'filepath': 'static/photos/gallery/dunes.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach in Oregon'
    },
    {
        'filepath': 'static/photos/gallery/emergencyRoom.jpg',
        'location': 'Pasco, WA',
        'caption': 'Hospital in Pasco'
    },
    {
        'filepath': 'static/photos/gallery/FerrisWheelWashington.jpg',
        'location': 'Spokane, WA',
        'caption': 'Ferris Wheel in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/flower.jpg',
        'location': 'The Dalles, OR',
        'caption': 'A flower found at Mayer State Park'
    },
    {
        'filepath': 'static/photos/gallery/fourthOfJulySmoke.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Fireworks for the 4th of July in on the Ocean.'
    },
    {
        'filepath': 'static/photos/gallery/gardensOne.jpg',
        'location': 'Spokane, WA',
        'caption': 'Botanical Gardens at Manito Park'
    },
    {
        'filepath': 'static/photos/gallery/gardensTwo.jpg',
        'location': 'Spokane, WA',
        'caption': 'Botanical Gardens at Manito Park'
    },
    {
        'filepath': 'static/photos/gallery/home_page2.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'River along campsite in Depoe Bay'
    },
    {
        'filepath': 'static/photos/gallery/lake.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Sunset at park in Kennewick, WA'
    },
    {
        'filepath': 'static/photos/gallery/landing_page.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach in Depoe Bay, OR'
    },
    {
        'filepath': 'static/photos/gallery/me_at_beach.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Me on beach in Depoe Bay, OR'
    },
    {
        'filepath': 'static/photos/gallery/meGumWall.jpg',
        'location': 'Seattle, WA',
        'caption': 'Me at the Gum Wall in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/meowtropolitan.jpg',
        'location': 'Seattle, WA',
        'caption': 'Seattle Meowtropolitan'
    },
    {
        'filepath': 'static/photos/gallery/middleOfNowhereLake.jpg',
        'location': 'Unknown',
        'caption': 'Middle of Nowhere Lake'
    },
    {
        'filepath': 'static/photos/gallery/oceanAgain.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Ocean in Depoe Bay'
    },
    {
        'filepath': 'static/photos/gallery/oceanYetAgain.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Ocean in Depoe Bay'
    },
    {
        'filepath': 'static/photos/gallery/oneTree.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Tree at a park in Kennewick'
    },
    {
        'filepath': 'static/photos/gallery/oregonHotel.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'View from hotel on Oreogn coast'
    },
    {
        'filepath': 'static/photos/gallery/oregonHotelTwo.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Hotel on Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/OregonOutlookSign.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Outlook sign at hotel on Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/pathGreen.jpg',
        'location': 'Spokane, WA',
        'caption': 'A path at River Front Park'
    },
    {
        'filepath': 'static/photos/gallery/piano.jpg',
        'location': 'Spokane, WA',
        'caption': 'Inside the cathedral in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/pierL.jpg',
        'location': 'Leavenworth, WA',
        'caption': 'The river in Leavenworth'
    },
    {
        'filepath': 'static/photos/gallery/publicMarket.jpg',
        'location': 'Seattle, WA',
        'caption': 'Public Market in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/riverTwo.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Columbia River in Kennewick'
    },
    {
        'filepath': 'static/photos/gallery/rocksAndOcean.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach on Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/seattle.jpg',
        'location': 'Seattle, WA',
        'caption': 'Street view in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/spaceNeedle.jpg',
        'location': 'Seattle, WA',
        'caption': 'The Space Needle in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/steph.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'My anniversary with my girlfriend on the Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/sunset_me.jpg',
        'location': 'Kennewick, WA',
        'caption': 'Me at a park in Kennewick watching the sunset'
    },
    {
        'filepath': 'static/photos/gallery/treeOutlook.jpg',
        'location': 'Newport, OR',
        'caption': 'Devils Punch Bowl outlook on Oregon Coast'
    },
    {
        'filepath': 'static/photos/gallery/trees.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Campground on the Oregon coast'
    },
    {
        'filepath': 'static/photos/gallery/view.jpg',
        'location': 'Fort Worth, TX',
        'caption': 'View from apartment overlooking the river in Texas'
    },
    {
        'filepath': 'static/photos/gallery/vines.jpg',
        'location': 'Seattle, WA',
        'caption': 'City center in Seattle'
    },
    {
        'filepath': 'static/photos/gallery/washingtonWaterPower.jpg',
        'location': 'Spokane, WA',
        'caption': 'Washington Water Power in Spokane'
    },
    {
        'filepath': 'static/photos/gallery/waves.jpg',
        'location': 'Depoe Bay, OR',
        'caption': 'Beach on the Oregon coast'
    }
]

flaskblog/main/routes.py
from flask import render_template, request, Blueprint
from flaskblog.models import Post

main = Blueprint('main', __name__)



blog=" "
gallery=" "

# @main.route("/")
# def index():
#     return render_template('index.html', title="Home")

@main.route("/about")
def about():
    return render_template('about.html', title='About', about=about)

@main.route("/")
def blog():
    page = request.args.get('page', 1, type=int)
    per_page = 5
    posts = Post.query.order_by(Post.date_posted.asc()).paginate(page, per_page)
    return render_template('blog.html', posts=posts, title="Blog", blog=blog)

flaskblog/posts/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db, basic_auth
from flask_basicauth import BasicAuth
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm
import sys

posts = Blueprint('posts', __name__)

@posts.route("/programming")
def topic_programming():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_programming.html', stories=stories, title='Topic: Programming')

@posts.route("/frameworks")
def topic_frameworks():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_frameworks.html', stories=stories, title='Topic: Frameworks')

@posts.route("/libraries")
def topic_libraries():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_libraries.html', stories=stories, title='Topic: Libraries')

@posts.route("/algorithms")
def topic_algorithms():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_algorithms.html', stories=stories, title='Topic: Algorithms')

@posts.route("/data")
def topic_data():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_data.html', stories=stories, title='Topic: Data-Structures')

@posts.route("/projects")
def topic_projects():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_projects.html', stories=stories, title='Topic: Projects')

@posts.route("/film")
def topic_film():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_film.html', stories=stories, title='Topic: Film')

@posts.route("/thoughts")
def topic_thoughts():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_thoughts.html', stories=stories, title='Topic: Thoughts')

@posts.route("/diy")
def topic_diy():
    p = request.args.get('p', 1, type=int)
    pp = 300
    stories = Post.query.order_by(Post.date_posted.asc()).paginate(p, pp)
    return render_template('topic_diy.html', stories=stories, title='Topic: DIY')

flaskblog/project/routes.py
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db, basic_auth
from flask_basicauth import BasicAuth
from flaskblog.models import Project
from flaskblog.project.forms import ProjectForm
from flaskblog.users.utils import save_picture

proj = Blueprint('proj', __name__)

#new
project = ""

@proj.route("/project")
def project():
    project = Project.query.order_by(Project.title.desc())
    return render_template('projects.html', title='Projects', project=project)

# data

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.blog'))
        else:
            flash('Login Unsuccessful. Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout", methods=['GET', 'POST'])
def logout():
    logout_user()
    return redirect(url_for('main.blog'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

# enter email to request a password reset
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

# reset password with token
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.blog'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block about %}
<div class="container col-md-12">
  <header class="header col-md-12">
      <p class="header-intro my-primary">Hi, I'm</p>
      <h1 class="header-name my-primary">Jason</h1>
    </div>
  </header>

  <section class="about text-white col-md-4">
    <h2 class="text-white">Introduction</h2>
    <br>
    <p>
      Hi, so a little about me. I live in Richland, Washington with my
      girlfriend and am the lucky dad of two cats [jesska and milo]; as well as
      one turtle [marilyn].
    </p>

    <p>
      I received my BS of Computer Science from Jackson State University in
      December of 2017. I have worked at Lockheed Martin as a Software Engineer from
      graduation until the end of January 2020.
    </p>

    <p>
      If you have any questions or are interested in working with me then please
      reach out to me at: jsonbytesllc@gmail.com.
    </p>
  </section>

  <footer class="footer col-md-12">
    <ul class="social">
      <li class="my-primary"><a href="https://github.com/JsonTyler" target="_blank">Github</li>
      <li><a href="https://www.linkedin.com/in/jason-bruno/" target="=_blank">LinkedIn</li>
      <li><a href="https://www.youtube.com/" target="_blank">Youtube</li>
    </ul>
  </footer>
</div>
{% endblock about %}

flaskblog/templates/blog.html
{% extends "layout.html" %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section-main">
          <div class="media-body">
              <img class="rounded-circle article-img float-left" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
            <div class="article-metadata">
              <span class="icon ">
                <i class="fas fa-user"></i>
              </span>
              <a class="mr-2" href="{{ url_for('main.about') }}">{{ post.author.username }}</a>

              <span class="icon ">
                <i class="fas fa-calendar"></i>
              </span>

              <a class="mr-2 text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</a>
	      


              <span class="icon ">
                <i class="fas fa-tags"></i>
              </span>
              <a class="mr-2 text-muted badge badge-light" href="{{ post.topic.value }}">{{ post.topic.value }}</a>

            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <img src="{{ post.image }}" width="100%" height=auto>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4 bg-light text-dark" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4 bg-light text-dark" href="{{ url_for('main.blog', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
      <a class="text-white">...</a>
      {% endif %}
    {% endfor %}
{% endblock content %}

<!-- {% block sidebar %}
<div class="content-section-sidebar">
  <a class="text-muted">Categories</a>
    <ul class="list-group">
        <a class="text-muted" href="{{ url_for('posts.topic_programming') }}">Programming</a>
        <a class="text-muted" href="{{ url_for('posts.topic_frameworks') }}">Frameworks</a>
        <a class="text-muted" href="{{ url_for('posts.topic_libraries') }}">Libraries</a>
        <a class="text-muted" href="{{ url_for('posts.topic_algorithms') }}">Algorithms</a>
        <a class="text-muted" href="{{ url_for('posts.topic_data') }}">Data-Structures</a>
        <a class="text-muted" href="{{ url_for('posts.topic_projects') }}">Projects</a>
        <a class="text-muted" href="{{ url_for('posts.topic_film') }}">Film/Editing</a>
        <a class="text-muted" href="{{ url_for('posts.topic_thoughts') }}">Thoughts/Ideas</a>
        <a class="text-muted" href="{{ url_for('posts.topic_diy') }}">DIY</a>
    </ul>
</div>
{% endblock sidebar %} -->

flaskblog/templates/gallery.html
{% extends "layout.html" %}
<h1 class="text-light">Gallery Page</h1>
{% block gall %}
<div class="container-fluid pt-2">
  <div class="card-columns">
    {% for img in gallery %}
    <div class="card">
      <a href="{{ url_for('static', filename=img.filepath) }}" data-toggle="demolightbox" data-title= "{{ img.location }}" data-footer="{{ img.caption }}"/>
      <img class="card-img-top img-responsive" style="width:100%; height: auto;" src={{ url_for('static', filename=img.filepath) }} />
    </div>
    {% endfor %}
  </div>
</div>
{% endblock gall %}

flaskblog/templates/topic_data.html
{% extends "layout.html" %}

{% block topic_data %}
    {% for story in stories.items %}
      {% if story.topic.value == 'data' %}
        <article class="media content-section-main">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + story.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">

              <span class="icon ">
                <i class="fas fa-user"></i>
              </span>
              <a class="mr-2" href="{{ url_for('main.about') }}">{{ story.author.username }}</a>

              <span class="icon ">
                <i class="fas fa-calendar"></i>
              </span>

              <a class="mr-2 text-muted">{{ story.date_posted.strftime('%Y-%m-%d') }}</a>
	      
              <span class="icon ">
                <i class="fas fa-tags"></i>
              </span>
              <a class="mr-2 text-muted badge badge-light">{{ story.topic.value }}</a>

            </div>
            <h2><a class="article-title" href="#">{{ story.title }}</a></h2>
            <img src="{{ story.image }}" width="100%" height=auto>
            <p class="article-content">{{ story.content }}</p>
          </div>
        </article>
      {% endif %}
    {% endfor %}
{% endblock topic_data %}

{% block sidebar %}
<div class="content-section-sidebar">
  <a class="text-muted">Categories</a>
    <ul class="list-group">
        <a class="text-muted" href="{{ url_for('posts.topic_programming') }}">Programming</a>
        <a class="text-muted" href="{{ url_for('posts.topic_frameworks') }}">Frameworks</a>
        <a class="text-muted" href="{{ url_for('posts.topic_libraries') }}">Libraries</a>
        <a class="text-muted" href="{{ url_for('posts.topic_algorithms') }}">Algorithms</a>
        <a class="text-muted" href="{{ url_for('posts.topic_data') }}">Data-Structures</a>
        <a class="text-muted" href="{{ url_for('posts.topic_projects') }}">Projects</a>
        <a class="text-muted" href="{{ url_for('posts.topic_film') }}">Film/Editing</a>
        <a class="text-muted" href="{{ url_for('posts.topic_thoughts') }}">Thoughts/Ideas</a>
        <a class="text-muted" href="{{ url_for('posts.topic_diy') }}">DIY</a>
    </ul>
</div>
{% endblock sidebar %}

flaskblog/templates/topic_diy.html
{% extends "layout.html" %}

{% block topic_diy %}
    {% for story in stories.items %}
      {% if story.topic.value == 'diy' %}
        <article class="media content-section-main">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + story.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">

              <span class="icon ">
                <i class="fas fa-user"></i>
              </span>
              <a class="mr-2" href="{{ url_for('main.about') }}">{{ story.author.username }}</a>

              <span class="icon ">
                <i class="fas fa-calendar"></i>
              </span>

              <a class="mr-2 text-muted">{{ story.date_posted.strftime('%Y-%m-%d') }}</a>
	      
              <span class="icon ">
                <i class="fas fa-tags"></i>
              </span>
              <a class="mr-2 text-muted badge badge-light">{{ story.topic.value }}</a>

            </div>
            <h2><a class="article-title" href="#">{{ story.title }}</a></h2>
            <img src="{{ story.image }}" width="100%" height=auto>
            <p class="article-content">{{ story.content }}</p>
          </div>
        </article>
      {% endif %}
    {% endfor %}
{% endblock topic_diy %}

{% block sidebar %}
<div class="content-section-sidebar">
  <a class="text-muted">Categories</a>
    <ul class="list-group">
        <a class="text-muted" href="{{ url_for('posts.topic_programming') }}">Programming</a>
        <a class="text-muted" href="{{ url_for('posts.topic_frameworks') }}">Frameworks</a>
        <a class="text-muted" href="{{ url_for('posts.topic_libraries') }}">Libraries</a>
        <a class="text-muted" href="{{ url_for('posts.topic_algorithms') }}">Algorithms</a>
        <a class="text-muted" href="{{ url_for('posts.topic_data') }}">Data-Structures</a>
        <a class="text-muted" href="{{ url_for('posts.topic_projects') }}">Projects</a>
        <a class="text-muted" href="{{ url_for('posts.topic_film') }}">Film/Editing</a>
        <a class="text-muted" href="{{ url_for('posts.topic_thoughts') }}">Thoughts/Ideas</a>
        <a class="text-muted" href="{{ url_for('posts.topic_diy') }}">DIY</a>
    </ul>
</div>
{% endblock sidebar %}

flaskblog/templates/topic_film.html
{% extends "layout.html" %}

{% block topic_film %}
    {% for story in stories.items %}
      {% if story.topic.value == 'film' %}
        <article class="media content-section-main">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + story.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">

              <span class="icon ">
                <i class="fas fa-user"></i>
              </span>
              <a class="mr-2" href="{{ url_for('main.about') }}">{{ story.author.username }}</a>

              <span class="icon ">
                <i class="fas fa-calendar"></i>
              </span>

              <a class="mr-2 text-muted">{{ story.date_posted.strftime('%Y-%m-%d') }}</a>
	      
              <span class="icon ">
                <i class="fas fa-tags"></i>
              </span>
              <a class="mr-2 text-muted badge badge-light">{{ story.topic.value }}</a>

            </div>
            <h2><a class="article-title" href="#">{{ story.title }}</a></h2>
            <img src="{{ story.image }}" width="100%" height=auto>
            <p class="article-content">{{ story.content }}</p>
          </div>
        </article>
      {% endif %}
    {% endfor %}
{% endblock topic_film %}

{% block sidebar %}
<div class="content-section-sidebar">
  <a class="text-muted">Categories</a>
    <ul class="list-group">
        <a class="text-muted" href="{{ url_for('posts.topic_programming') }}">Programming</a>
        <a class="text-muted" href="{{ url_for('posts.topic_frameworks') }}">Frameworks</a>
        <a class="text-muted" href="{{ url_for('posts.topic_libraries') }}">Libraries</a>
        <a class="text-muted" href="{{ url_for('posts.topic_algorithms') }}">Algorithms</a>
        <a class="text-muted" href="{{ url_for('posts.topic_data') }}">Data-Structures</a>
        <a class="text-muted" href="{{ url_for('posts.topic_projects') }}">Projects</a>
        <a class="text-muted" href="{{ url_for('posts.topic_film') }}">Film/Editing</a>
        <a class="text-muted" href="{{ url_for('posts.topic_thoughts') }}">Thoughts/Ideas</a>
        <a class="text-muted" href="{{ url_for('posts.topic_diy') }}">DIY</a>
    </ul>
</div>
{% endblock sidebar %}